language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: "ZUhFF9jYH4TwLNhsx+XepGqwrW/t2bVaaelWjvBaM+io93rt/gMfC06Zs7ZFVCMTkwtnKyYcPvIpc33V/dc6DNlrWgb4GLsWDMT0rktI4qtqOJhZkANX/U9M9JoMOHu+ScWU5BuhaycSG474euywjXrz5bkss2MMGr7Ap9uEwxrMsMFxio3FgMTilYWEN8z82Eqr6n1/FPMdb2TCCCuUSpzuilGmMRzIM0BXuqAnGNqophh3WBDPAh6ht63ve+AV1hoXlhRekYZ9SCQYaL+Gd3ba6d5oj6HmEoxpVLl+EyWDIgAh5hK3qo/wU1IKk9+1yDgFr5S5d2FxSYMsWqVlANSgtqc5/vsM1wR26muEYLhZaFzDKt8sFiqBADydBpyJZTZbT2jvP53mqhKcX5GuuiLV6s309Uq4PDIl22pRwAEr4wZcm4BbPxZO+2csoc9K4xLb7y57VQ9BkYsWMv80AYqRKUbIP6lfHbC3bwV4vcs/vIUi6Nu28vORQ123ioVpsqEIPhFMsLcfsm4w9VbefcyjR0cN01lOAviRMzo0steYn8TXtXCozfw03K2A7c38XaVFBTYOUXVL4n5+jJ7dcljPsanExy2d1/IEntpnheUD3SIOUmKG8wUG1AacE+IbGRcgp4fX42XvZRfW979X1/E0cHAwSgN283CuHt8F8Xo="